### ISSUE TITLE
Add solver option aliases

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#1]
(Copy of Issue 125 in the old repository)

We want to support aliases for the solver options. In particular the following ones:
`T` ~ `time_horizon`
`delta` ~ `sampling_time`
`plot_vars` ~ `output_variables`

**Comment by schillic** [comment]
I will leave this open until we have the plot options. Then I can revisit plot aliasing.

**Comment by schillic** [comment]
The current version (which was also merged to `master`) has the following bug:
The input `:N` is ignored.
This should be fixed by adding `check_aliases!(dict, dict_copy, [:N])` to `check_and_add_δ_N_T`.

**Comment by schillic** [comment]
I fixed a bug: If you used an alias, then it ignored the value and chose the default value 🤕

Furthermore I added the plot alias `output_variables` -> `plot_vars`.
I think this is all for the moment.

**Comment by mforets** [comment]
cool! and what do u think about `time_horizon` and `sampling_time`?

**Comment by schillic** [comment]
We already [support them](https://github.com/JuliaReach/Reachability.jl/blob/476ff6714717684a21c2ea5c379fa8e07b995638/src/options.jl#L215).

I close this; we can easily add new aliases now.
