### ISSUE TITLE
Add convenience options for partition and set types

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#114]
Instead of having to provide the partition and the set type, a user may just want to pick a template.

* `"1D"` = 1D blocks with `Interval` type (or `Hyperrectangle` if it is actually faster)
* `"2D"` = 2D blocks with either `HPolygon` if some `:ε` has been defined, and `Hyperrectangle` otherwise
* `"nD"`, which just creates a single block (currently we need `Hyperrectangle` here)

Is there more?
What would be a good name for this new option? Or should we just allow strings for `:partition` in the input?

**Comment by mforets** [comment]
i would keep `:partition` as it is now, so as not to introduce more `Union` types.

proposal: formulate what you say in this way:

- if `partition` is not given. if `set_type` is not given let it be `Hyperrectangle`.
    - if `set_type` is `Interval`=> define partition with `[i]`
    - if `set_type` is `HPolygon` => ... 2D
    - if `set_type` is `Hyperrectangle` => ... 2D

**Comment by schillic** [comment]
Ah ok, that's clever :+1:

**Comment by schillic** [comment]
I moved the comment to #92, which is basically the same.
