### ISSUE TITLE
Add option to control number of threads used by OpenBLAS

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#131]
Even though we currently do not use parallel computing features, Julia often uses all my four cores. We should understand why.

I observed it during discretization, decomposition, and image computation for dense matrices (but not for sparse matrices). First guess: dense matrix multiplication (Julia internal)

**Comment by schillic** [comment]
> First guess: dense matrix multiplication (Julia internal)

[Bingo](https://stackoverflow.com/a/33947068).

Now we should find out if we can somehow deactivate this "feature" for better comparison to other tools (and for evaluating #69).

**Comment by schillic** [comment]
> Now we should find out if we can somehow deactivate this "feature"

[`Base.LinAlg.BLAS.set_num_threads(n)`](https://docs.julialang.org/en/stable/stdlib/linalg/#Base.LinAlg.BLAS.set_num_threads) is our friend. It works :+1:

**Comment by mforets** [comment]
there is the function [get_num_threads](https://github.com/JuliaLang/julia/blob/251a501def6a52d497784ad1ca8206579d814bce/stdlib/Distributed/test/distributed_exec.jl#L918) for i coulnd't find it in my julia 0.6.1

however, this works:

```julia
julia> ccall((:openblas_get_num_threads64_, Base.libblas_name), Cint, ())
4
```

**Comment by schillic** [comment]
It does not work for me.

**Comment by mforets** [comment]
actually, `get_thun_threads()` is in a test of the `Distributed` module of julia's standard library. i'm afraid we cannot access this method.

**Comment by schillic** [comment]
We decided to not change the number of threads internally. The user is required to do that manually.
