### ISSUE TITLE
Revise `Union{ConstantInput, Void}`

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#140]
Instead of `U::Union{ConstantInput, Void}`, make the input to contain `nothing`.

EDIT: i think this would amount to chaning:

```julia
    if !assume_homogeneous && inputdim(S) > 0
        U = inputset(S)
    else
        U = ConstantInput(nothing) # we wrap around a constant input
    end
    push!(args, U)
```

since

```julia
julia> ConstantInput(nothing)
Systems.ConstantInput{Void}(nothing)
```

I don't know though if algorithms like

```julia
function reach_blocks!(ϕ::SparseMatrixCSC{NUM, Int},
                       Xhat0::Vector{<:LazySet{NUM}},
                       U::ConstantInput,
                       overapproximate::Function,
                       n::Int,
                       N::Int,
                       blocks::AbstractVector{Int},
                       partition::AbstractVector{<:Union{AbstractVector{Int}, Int}},
                       res::Vector{CartesianProductArray{NUM}}
                       )::Void where {NUM}
```

still compile separate versions with and without input; ie. the difference with `U::Union{ConstantInput, Void}` as argument.

i think the "julian" way is just to make a new function `reach_blocks!` that dispatches on its arguments, as we had before.

**Comment by schillic** [comment]
> Instead of U::Union{ConstantInput, Void}, make the input to contain nothing.

Why?

> i think the "julian" way is just to make a new function reach_blocks! that dispatches on its arguments, as we had before.

But this was the whole idea.
