### ISSUE TITLE
Option: Sparse/dense matrix conversion

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#143]
proposal: remove the `try`.

```
        if options[:assume_sparse] && !(Δ.s.A isa SparseMatrixCSC)
            A = sparse(Δ.s.A)
        elseif options[:assume_sparse] && !(Δ.s.A isa Matrix)
            A = full(Δ.s.A)
       else
            A = nothing
       end
       if A != nothing
           Δ = DiscreteSystem(A, Δ.x0, inputset(Δ))
       end
```

**Comment by schillic** [comment]
There are more than just two types of matrices in the world. Are we sure that this conversion will never crash? But it is a step forward :+1:

**Comment by mforets** [comment]
How about using `method_exists`:

```julia
A = Δ.s.A
if options[:assume_sparse]
    if method_exists(length, Tuple{typeof(Δ.s.A)})
        A = sparse(Δ.s.A)
    else
        error("cannot apply `assume_sparse` option to a matrix of type $(typeof(Δ.s.A))")
    end
end
Δ = DiscreteSystem(A, Δ.x0, inputset(Δ))
```

note that in this code, if `assume_sparse` is false, we don't do anything. i'm not sure what we want to do with this `assume_sparse` option. it doesn't have `nothing` (ignore it) default value.

**Comment by schillic** [comment]
> note that in this code, if assume_sparse is false, we don't do anything.

Actually, you still create a new system. I think you can pull the last line indisde the `if`.

And I would not raise an error. Should we rather pass the `assume_sparse` option to the `reach_blocks` functions for dispatch? There we are not really interested in the matrix type. This would also be useful for #89.

**Comment by mforets** [comment]
agreed, let's just raise a warning to say that the option is inconsistent and is being ignored.

 > Should we rather pass the assume_sparse option to the reach_blocks functions for dispatch? 

for this particular option i would preprocess it in `reach` and send to the appropriate solver using multiple dispatch in the line `available_algorithms[algorithm_backend]["func"](args...)`.
