### ISSUE TITLE
Add default value for :vars

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#165]
Currently we require this option. The default should be `1:n`.

**Comment by mforets** [comment]
It now the case that the `:vars` option in BFFPSV18 is not mandatory and defaults to all variables, see https://github.com/JuliaReach/Reachability.jl/blob/ce931c1ace974458b1d208e854320a8ff9efdb69/src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl#L33

**Comment by schillic** [comment]
This was changed in #234.
