### ISSUE TITLE
Simplify overapproximation options

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#196]
In #194 we added template directions, but they currently cannot be combined with other approximations for different blocks.
Revise the way a user chooses the overapproximation.

This should be done together with #87 (which is the internal representation).

Maybe #92 should also be considered here.

**Comment by mforets** [comment]
see also [this comment](https://github.com/JuliaReach/Reachability.jl/pull/195#issuecomment-390881041)

**Comment by schillic** [comment]
Alternatively we could rather let `LazySets.jl` resolve the different inputs, see [#345](https://github.com/JuliaReach/LazySets.jl/issues/345).

**Comment by schillic** [comment]
This was resolved in #505.
