### ISSUE TITLE
Add plot solution recipe

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#2]
We add a new `@recipe plot_solution(sol::Vector{HPolygon})`.

This is on hold until we build the LazySets.jl plotting recipes.

**Comment by mforets** [comment]
shall we have a "solution" structure? currently in `t/mforets/2`  the following problem:

```julia
using Reachability, Plots
A = randn(4, 4); X0 = BallInf(ones(4), 0.1)
s = solve(ContinuousSystem(A, X0), :T=>0.1);
plot(s)
```
falls back to `LazySets` plot array of polygons, instead of the one defined in Reachability.

**Comment by schillic** [comment]
I do not know what a solution structure is.

**Comment by mforets** [comment]
something that wraps `polygons::Vector{HPolygon}, options::Options`.

unless we remove the recipe for a `Vector{HPolygon}` in `Polygon.jl`, only keeping the one for a single set. notice that in reachability we would like that `plot(s)` works, and it also adds default labels and stuff. so it has to access the options somehow.

**Comment by mforets** [comment]
we can begin with sth simple:

```julia
mutable struct RsetsProjSolution
  sets::Vector{HPolygon}
  opt::Options
end
```
then

```julia
@recipe plot_RsetsProjSolution(r::RsetsProjSolution)
        plot(r.sets, r.opt...) # shall open up the options as a list of values.. 
end

**Comment by schillic** [comment]
Understood. I would choose a different name. Just thinking aloud: `PlottableSet`?

**Comment by schillic** [comment]
Just a reminder: We still need to modify the models by adding a `using Plots`.

**Comment by schillic** [comment]
I get the following warning in master when I use the `Plots` package:
`WARNING: both Plots and Reachability export "plot"; uses of it in module Main must be qualified`

**Comment by mforets** [comment]
> Just a reminder: We still need to modify the models by adding a using Plots.

yes. we could discuss about removing that extra `using Plots` by reexporting `plots.` 

> I get the following warning in master 

i haven't merged to master, but in the latest push to the branch `t/mforets/2`, that warning is fixed and we can plot eg. the `unit_solve.jl` model, and `motor.jl` (remember  to checkout `LazySets.jl` too).

could you check the refactoring i made in `t/mforets/2`? it's just a start.

currently there is a basic plot recipe. to conclude it remains to incorporate back the features:

- indices for plotting a sampled array
- xlabel and ylabel from some model option

i thought about updating `validate_plot_options_and_add_default_values` to handle these two features.
