### ISSUE TITLE
Investigate recent slowdown in discretization

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#205]
FOM model:
```
[2018-05-25T15:07:38|info] Time discretization...
[2018-05-25T15:07:43|info] elapsed time: 5.265388876 seconds

[2018-05-28T16:47:09|info] Time discretization...
[2018-05-28T16:47:24|info] elapsed time: 14.53008289 seconds
```
First step: Go back in the history and check if this is reproducible.

**Comment by schillic** [comment]
For MNA5 it also takes longer (640 seconds vs. 320 seconds). It might be related to `lazy_expm` (but I did not try the other mode yet).

**Comment by schillic** [comment]
I do not remember recent changes that affect the discretization. Maybe it was a change in `LazySets`...

**Comment by mforets** [comment]
> Reset Reachability.jl to version 2b52341 for compatibility.

Great detective work.

This has been fixed in  https://github.com/JuliaReach/LazySets.jl/pull/357
