### ISSUE TITLE
Refactor `solve.jl`

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#230]
See https://github.com/JuliaReach/Reachability.jl/pull/228#discussion_r211182885

**Comment by mforets** [comment]
Currently `solve` has this interface:

```julia
solve(system::InitialValueProblem, options::Options)
```

Then:

1. Validate options
2. Call `reach` or `check` depending on the `options[:mode]`
3. Return the results as an `AbstractSolution`

I think an inconvenience of this approach is that some options only make sense for specific algorithms, eg. `:partition` is attached to the `"BFFPSV18"` only (HSCC'18).

OTOH if i want to pass the algorithm as `options[:algorithm]`, then `validate_solver_options_and_add_default_values!` says that there is no supported option `"algoritm"`.

An alternative is to pass the algorithm as a keyword:

```julia
solve(system::InitialValueProblem, options::Options; algorithm::String="BFFPSV18")
```

**Comment by schillic** [comment]
> I think an inconvenience of this approach is that some options only make sense for specific algorithms

Where is the inconvenience here? I find it very convenient as a user to have to pass only one `Options` object.

If you mean "inconvenient for the developer", we could split the validation in two stages:
1. general options (but this might only be `algorithm`)
2. algorithm-specific options
But IMO this should happen internally and not be exposed to the user.

> An alternative is to pass the algorithm as a keyword

Ideally we should eventually be able to choose the algorithm automatically. So I would not do that and keep the interface simple.

**Comment by mforets** [comment]
> Where is the inconvenience here? I find it very convenient as a user to have to pass only one Options object.

Point taken. Splitting the validation in two stages: generic options and algorithm-specific options make sense for me.
