### ISSUE TITLE
Discretization with mixed norms

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#252]
I saw that in the implementation of the "first-order" bloating model from the LGG paper we mix the norms (the ball is in the 2-norm, but for the matrix and `X0` we use the infinity norm). Is that "legal"?

https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/discretize.jl#L82

**Comment by mforets** [comment]
I haven't checked the details yet, but since in in finite-dimensional spaces all norms are equivalent, the difference is at most a constant factor depending on the dimension.
