### ISSUE TITLE
Wrong approach to initialise waiting list at the very beginning. 

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/Reachability.jl#283]
Currently we add only `loc1` and `X0` to the waiting list. However, we should add all locations from our system with the same `X0` to the waiting list. In addition, user should have an option to specify location via model file.

**Comment by schillic** [comment]
Actually, in general you should be able to define a different `X0` for each location. If not, then at least we have to take the intersection with the invariant (we might want to do that anyway).

**Comment by schillic** [comment]
A way to go is to change the input `X0` from a set to a mapping `loc -> X0_loc`, and then extract that correctly. What do you think?

**Comment by kostakoida** [comment]
I believe in SpaceEx we can define initial set only for one location. However, it could a nice feature to add possibility to choose initial set for each location in the system. The main question for me is whether such cases exist. I can`t imagine a model where we want to compute reachable set, based on different inputs for different modes.

**Comment by schillic** [comment]
Yes, you can do that in SpaceEx using disjunction and the `loc` function. Something like:
`(loc(component) == l5 & x < 5) | (loc(component) == l2 & x > 2)`

**Comment by kostakoida** [comment]
Oh, ok, I didn`t know about this feature. 
Then you`re right, we need to have a map `loc -> X0_loc`.

**Comment by schillic** [comment]
If no location is specified, SpaceEx considers *all* locations where the intersection is non-empty.
But we do not have to solve this problem in all generality here. Here are some valid approaches:
1. Add a way to specify *the only initial location*.
2. Add a way to specify a list of initial locations, all with the same initial set.
3. Add a way to specify a mapping from initial location to initial set.
4. Determine the location(s) automatically if no location is specified (probably requires some parsing etc. work).

**Comment by kostakoida** [comment]
I believe we want to implement the 3rd option and keep the 4th for the future?
