### ISSUE TITLE
Case study: Filtered oscillator

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#305]
* [x] no fixpoint found (#324)
* [x] continuous-time reachability analysis is very slow (with `:δ=>0.001` it takes >10 seconds; for a 4D system it should be nearly instantaneous)
* [x] lazy intersection operator is very slow (#308)

**Comment by schillic** [comment]
> no fixpoint found

The problem is that we do not initialize the `passed_list` with the initial set. However, we do not have to add the initial set, but we can actually add the initial approximation (which is bigger). Still, I do not understand why a fixpoint is not found after one more jump...

**Comment by mforets** [comment]
|system dimension|Operator|runtime|
|-------|------|------|
|4|TextbookDiscretePost (concrete)|3.34|
|4|ApproximatingDiscretePost|1.14|

**Comment by kostakoida** [comment]
|system 's dimension|Operator|runtime|
|-------|------|------|
|4|TextbookDiscretePost (concrete)|3.63|
|4|ApproximatingDiscretePost|1.59|
|6|TextbookDiscretePost (concrete)|32.43|
|6|ApproximatingDiscretePost|2.01|

**Comment by mforets** [comment]
For `n0=16` which is actually `system_dimension=18`,

```julia
# specify overapproximating discrete post operator
sol = solve(system, options_pr_t, Reachability.BFFPSV18(),
           Reachability.ReachSets.ApproximatingDiscretePost(
                Options(:overapproximation=>Hyperrectangle)));
```
2nd run takes ~17 seconds.

**Comment by schillic** [comment]
> 2nd run takes ~17 seconds

For me it takes 94 seconds. Have you recently upgraded your notebook? :racehorse:

**Comment by kostakoida** [comment]
Update: those numbers relates to wrong fixpoint check
<table class="tg" style="undefined;table-layout: fixed; width: 733px">
<colgroup>
<col style="width: 85px">
<col style="width: 155px">
<col style="width: 189px">
<col style="width: 200px">
<col style="width: 104px">
</colgroup>
  <tr>
    <th class="tg-s268" rowspan="2">system 's dimension</th>
    <th class="tg-s6z2" colspan="3">Operator</th>
    <th class="tg-s6z2" rowspan="2">SpaceEx</th>
  </tr>
  <tr>
    <td class="tg-s6z2">TextbookDP (concrete)</td>
    <td class="tg-s6z2">LazyTextbookDP</td>
    <td class="tg-baqh">ApproximatingDP</td>
  </tr>
  <tr>
    <td class="tg-s268">4</td>
    <td class="tg-s6z2">2.13</td>
    <td class="tg-s6z2">1.37</td>
    <td class="tg-baqh">0.39</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-s268">6</td>
    <td class="tg-s6z2">3.87</td>
    <td class="tg-s6z2">1.99</td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-s268">10</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2">27.39</td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-s268">18</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2">66.05</td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-s268">34</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2">268.22</td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">66</td>
    <td class="tg-baqh"></td>
    <td class="tg-baqh">1258.02</td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">130</td>
    <td class="tg-baqh"></td>
    <td class="tg-baqh">7746.58</td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
<tr>
    <td class="tg-0lax">196</td>
    <td class="tg-baqh"></td>
    <td class="tg-baqh"></td>
    <td class="tg-baqh"></td>
    <td class="tg-0lax"></td>
  </tr>
</table>

**Comment by schillic** [comment]
```
**********************************
C 2
  0.894706 seconds (2.13 M allocations: 95.368 MiB, 4.20% gc time)
**********************************
L 2
  0.350310 seconds (1.98 M allocations: 172.460 MiB, 14.11% gc time)
**********************************
A 2
  0.339383 seconds (2.34 M allocations: 209.085 MiB, 16.40% gc time)
**********************************
C 4
  2.218552 seconds (3.15 M allocations: 151.036 MiB, 2.50% gc time)
**********************************
L 4
  0.544078 seconds (2.99 M allocations: 280.878 MiB, 16.91% gc time)
**********************************
A 4
  0.565536 seconds (3.66 M allocations: 358.010 MiB, 19.54% gc time)
**********************************
**********************************
L 8
  1.472291 seconds (7.28 M allocations: 765.328 MiB, 19.83% gc time)
**********************************
A 8
  1.311873 seconds (8.28 M allocations: 912.771 MiB, 21.11% gc time)
**********************************
**********************************
L 16
 13.588063 seconds (125.52 M allocations: 8.042 GiB, 20.65% gc time)
**********************************
A 16
  3.429836 seconds (21.90 M allocations: 2.716 GiB, 24.17% gc time)
**********************************
**********************************
L 32
 28.538691 seconds (196.27 M allocations: 20.656 GiB, 23.63% gc time)
**********************************
A 32
 14.396815 seconds (83.72 M allocations: 12.818 GiB, 25.96% gc time)
**********************************
**********************************
L 64
98.851921 seconds (623.68 M allocations: 117.086 GiB, 21.42% gc time)
**********************************
A 64
80.511962 seconds (623.69 M allocations: 92.998 GiB, 21.79% gc time)
**********************************
**********************************
A 128
997.166988 seconds (6.82 G allocations: 1.052 TiB, 22.68% gc time)
```
