### ISSUE TITLE
GLPK solver warning

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/Reachability.jl#311]
List of:
`Warning: numerical instability (primal simplex, phase II)` is displayed when you run FilteredOscillator.jl from the `ReachabilityBenchmarks` repo with system dimension 6 (2 + 4)

**Comment by mforets** [comment]
`sol = solve(system, options_input);` or `sol = solve(system, options_input, Reachability.BFFPSV18(),Reachability.ReachSets.LazyTextbookDiscretePost());`?

**Comment by kostakoida** [comment]
`sol = solve(system, options_input);`

There is just a long lust of such warnings

**Comment by schillic** [comment]
The problem was probably related to #317.
