### ISSUE TITLE
[Approx_alg]Extra overapproximation after transition, which change the dynamic of the system

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/Reachability.jl#325]
Concrete:
<img width="640" alt="concr" src="https://user-images.githubusercontent.com/7996008/46943257-f8b66e80-d0ba-11e8-9894-4b3af2ad1c3c.png">
0 jumps:
<img width="403" alt="screen shot 2018-10-15 at 8 53 55 pm" src="https://user-images.githubusercontent.com/7996008/46943967-9c544e80-d0bc-11e8-9590-cb69449ab0b9.png">
1 jump:
<img width="325" alt="screen shot 2018-10-15 at 8 54 29 pm" src="https://user-images.githubusercontent.com/7996008/46943968-9c544e80-d0bc-11e8-97b7-a9addc4b78e9.png">

Approx:
<img width="635" alt="approx" src="https://user-images.githubusercontent.com/7996008/46943251-f7854180-d0ba-11e8-9f3f-f34aff3b5a9c.png">
0 jumps:
<img width="403" alt="screen shot 2018-10-15 at 8 54 04 pm" src="https://user-images.githubusercontent.com/7996008/46943995-ad04c480-d0bc-11e8-8144-5fbfadfbcf46.png">
1 jump:
<img width="436" alt="screen shot 2018-10-15 at 8 54 41 pm" src="https://user-images.githubusercontent.com/7996008/46943996-ad04c480-d0bc-11e8-91d9-37b1e155ba80.png">

**Comment by schillic** [comment]
Wow, that seriously looks like a bug. The initial set after the jump should contain the set before the jump.

**Comment by schillic** [comment]
I noticed a strange behavior when changing the time horizon. The sets seem to move around and grow.

`T=0.74` (just one step after the transition):
![fo_t-0-74](https://user-images.githubusercontent.com/9656686/46996995-baeb3180-d11e-11e8-819e-704a31f8ff99.png)

`T=0.9`:
![fo_t-0-9](https://user-images.githubusercontent.com/9656686/46997005-c5a5c680-d11e-11e8-9793-b239706fd3ba.png)

`T=1.2`:
![fo_t-1-2](https://user-images.githubusercontent.com/9656686/46997008-c9394d80-d11e-11e8-9687-0a00e4b25594.png)

**Comment by schillic** [comment]
The "problem" is that we used box directions for the "Approx." operator. The result with octagon directions looks good.

![fo_approx_oct](https://user-images.githubusercontent.com/9656686/47000372-6b116800-d128-11e8-9aa8-dd133266a554.png)
