### ISSUE TITLE
LazyTextbookdDiscretePost approximation error is huge

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#326]
Bouncing ball:
In purple are the concrete and the overapproximating operators (they produce the same sets).
In red is the lazy operator.

![bouncing_ball_all](https://user-images.githubusercontent.com/9656686/46945451-17921200-d075-11e8-91dc-f89a451a0ddb.png)

**Comment by schillic** [comment]
Note that [this behavior came with the change to `HPolyhedron`](https://github.com/JuliaReach/Reachability.jl/issues/308#issuecomment-429631762). Identifying the difference of methods involved will likely show the problem.

**Comment by mforets** [comment]
this is solved by now:

<img width="642" alt="screen shot 2018-10-20 at 10 04 27" src="https://user-images.githubusercontent.com/12424594/47256024-90b3af80-d44f-11e8-8693-2dc082cbf19b.png">
