### ISSUE TITLE
Default dirs in ApproximatingDiscretePost

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#342]
[In this line](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/DiscretePost/DiscretePost.jl#L71), the directions for the convex hull are hardcoded to be `Hyperrectangle.` 

proposal 1) should we use instead the corresponding directions from the `options` variable, ie `options[:template_directions]`

proposal 2) should we default `Hyperrectangle` in [this line](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl#L11)?

**Comment by schillic** [comment]
Let me note that `dirs` can be misleading, as we also support set types there. I would rather like to change this interface to an option called `(over)approximation`, which can generally be a tuple of several settings like the approximation error. Internally we can of course change the representation.

**Comment by mforets** [comment]
For option 1) im not sure that `sol.options[:template_directions_init]` or `sol.options[:template_directions_iter]` are always defined, at least they do not exist in `keys(sol.options)` after

```julia
@time sol = solve(system, options_pr_t, Reachability.BFFPSV18(),
Reachability.ReachSets.ApproximatingDiscretePost(Options(:overapproximation=>Hyperrectangle)));
```

**Comment by schillic** [comment]
After fixing #80, we should not modify the input options anymore.

**Comment by mforets** [comment]
i was checking the options in `sol`, not those of `options_pr_t`.

**Comment by schillic** [comment]
Then we only set these options if no other option was found, see [here](https://github.com/JuliaReach/Reachability.jl/blob/master/src/options.jl#L604).

**Comment by mforets** [comment]
ok. correct, i was confused, the option to be used is the internal `overapproximation` of the discrete operato.

proposal 1 and 2 above are:

```julia
$ git diff
diff --git a/src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl b/src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
index c2c3334..5ae7ce0 100644
--- a/src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
+++ b/src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
@@ -8,7 +8,7 @@ struct ApproximatingDiscretePost <: DiscretePost
 end


 ApproximatingDiscretePost() =
-    ApproximatingDiscretePost(Options(:overapproximation => :oct))
+    ApproximatingDiscretePost(Options(:overapproximation => Hyperrectangle))

 function init(op::ApproximatingDiscretePost, system, options_input)
     options_input.dict[:n] = statedim(system, 1)
diff --git a/src/ReachSets/DiscretePost/DiscretePost.jl b/src/ReachSets/DiscretePost/DiscretePost.jl
index fc7d35b..684f1a9 100644
--- a/src/ReachSets/DiscretePost/DiscretePost.jl
+++ b/src/ReachSets/DiscretePost/DiscretePost.jl
@@ -60,6 +60,7 @@ function cluster(op::DiscretePost,
                  reach_sets::Vector{ReachSet{LazySet{N}, N}},
                  options::Options) where N<:Real
     clustering_strategy = options[:clustering]
+    dirs = op.options.[:overapproximation]
     if clustering_strategy == :none
         # no clustering
         return reach_sets
@@ -69,7 +70,7 @@ function cluster(op::DiscretePost,
         chull = ConvexHullArray(
             LazySet{N}[reach_set.X for reach_set in reach_sets])
         chull_oa = overapproximate(chull,
-                                   Hyperrectangle)
+                                   dirs)
         return [ReachSet{LazySet{N}, N}(chull_oa, reach_sets[1].t_start,
                 reach_sets[end].t_end)]
     end
```
