### ISSUE TITLE
Misuse of ConstrainedLinearControlXSystems

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#348]
We use the `ConstrainedLinearControlContinuousSystem` to pass the initial states. However, the constraint is supposed to hold for all times, i.e., to be an invariant.

Furthermore, we completely ignore the matrix `B`, so the user needs to pass `B*U` directly.

**Comment by mforets** [comment]
@schillic I think that we can now close this, do you agree? 

Related to the first statement (invariant) we have https://github.com/JuliaReach/Reachability.jl/issues/507. The second one was fixed in https://github.com/JuliaReach/Reachability.jl/pull/542.
