### ISSUE TITLE
:verbosity not listed in available options

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#37]
`keys(Reachability.available_keywords.dict)` lists all available options but `:verbosity`.

Furthermore, using this option leads to `Unrecognized option 'verbosity' found.` 😝

**Comment by schillic** [comment]
A minor issue that can also be fixed here: `approx_model` is documented twice.

**Comment by mforets** [comment]
moreover `keys(Reachability.available_keywords.dict)` is only available *after* calling a solve option. this is awkard since one would like to know the available options before calling `solve`. we should also say about `available_keywords` in the `solve`'s docstring.

**Comment by schillic** [comment]
I outsourced the "available options" task to #78 so we can close this issue.
