### ISSUE TITLE
Type not preserved in solve!

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#400]
The default value of `invariant` induces a type instability because `ZeroSet(n)` is `Float64`, see [this line](https://github.com/JuliaReach/Reachability.jl/blob/master/src/solve.jl#L76).

We should rather make a `ZeroSet{N}(n)` where `N` is the element type of the system, but i'm not sure how to do this properly..

**Comment by schillic** [comment]
`ZeroSet` is anyway weird here!

**Comment by mforets** [comment]
If there is no invariant, it should rather be the universal set. An empty hpolyhedron?

**Comment by schillic** [comment]
Yes! I am also a fan of adding `Universe` in `LazySets` for such purposes.

**Comment by mforets** [comment]
`Universe` is an ambitious type 😄

**Comment by schillic** [comment]
I bet I wanted to use `EmptySet` here and for some reason used `ZeroSet`.

> I would suggest that if it's only for this purpose we use nothing as the invariant's default.

Okay, the only downside is type instability.

**Comment by schillic** [comment]
This was resolved in #401.
