### ISSUE TITLE
Refactor hybrid models in tests

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#404]
Proposal: refactor tests in a folder that define models, and another folder that defines methods for them (`solve`, etc).

For the hybrid models, the following lines are used:

```julia
# default algorithm
sol = solve(system, options);

# specify lazy discrete post operator
sol = solve(system, options, BFFPSV18(), LazyDiscretePost());

# specify overapproximating discrete post-operator algorithm
sol = solve(system, options, BFFPSV18(), ApproximatingDiscretePost());
```

So one would call these functions in a loop for each `system` taken from a pool of tests systems.

**Comment by schillic** [comment]
Creating systems should not be the concern of this package, so I am not sure if we need such tests at all.

**Comment by schillic** [comment]
While we are at it, we can also adapt the folder structure in the `test` folder to the recent changes in the `src` folder.
