### ISSUE TITLE
Refactoring: replace systems implementation by Systems.jl

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#41]
Possible problem: The discrete system does not store `δ`.

**Comment by mforets** [comment]
one workaround would be to compose the `InitialValueProblem` type with a step size `δ`, like

```julia
struct AffineODE <: AbstractSystem
    ivp::IVP
    δ::Float64
end
```

**Comment by schillic** [comment]
Is it necessary that the system knows the `δ`?

**Comment by mforets** [comment]
i don't think it's completely necessary.. maybe we could just pass around `δ`.

**Comment by schillic** [comment]
I would prefer this over a hack.
