### ISSUE TITLE
Publications link is broken

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#418]
From the README.md, [Publications using JuliaReach](http://juliareach.github.io/Reachability.jl/latest/publications.html).

**Comment by schillic** [comment]
You did not solve this problem.

**Comment by mforets** [comment]
I think that the `gh-pages` branch hasn't been (automatically) updated yet; i don't see the new pages here https://juliareach.github.io/Reachability.jl/latest/

**Comment by schillic** [comment]
True, sorry, now it works!
