### ISSUE TITLE
Refactor properties

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#450]
Move "upwards" the `Properties` folder and gather the generic types (such as `CheckSolution`, `IntersectionProperty` and `LinearConstraintProperty`) and functions (such as `check_property` and `tune_δ`).

The remaining algorithm-specific methods can stay in in `ContinuousPost/BFFPSV18`, i guess.

**Comment by schillic** [comment]
Actually we moved the folder `Properties` into `ReachSets` not too long ago. I think it should not be useful as a standalone module (maybe for the types, but not for the functions).
