### ISSUE TITLE
Use input matrix from system

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#457]
Currently we expect LTI systems with invariants given as a `ConstrainedLinearControlContinuousSystem`, as in `ConstrainedLinearControlContinuousSystem(A, B, X, B*U)`. However, the `B` matrix (second argument) is completely ignored, and instead the user has to pass `B*U` as the fourth argument.

**Comment by mforets** [comment]
Fixed in https://github.com/JuliaReach/Reachability.jl/pull/542.
