### ISSUE TITLE
Default set type

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#487]
Interval creation is much faster than hyperrectangle creation. Proposal: use Interval by default if `vars` talks about only 1 variable.

**Comment by schillic** [comment]
We could also define a default value for `block_types` which uses `Interval`s for all 1D blocks. The problem is that we need the `partition` for that.
But this whole overapproximation stuff should be revised in #471 anyway.

**Comment by schillic** [comment]
This has been resolved in #505.
