### ISSUE TITLE
Support for hybrid systems with homogeneous dynamics

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#491]
Currently the analysis crashes [here](https://github.com/JuliaReach/Reachability.jl/blob/89bcb6fe9ec5177cd901c8092e8a990e122f46df/src/solve.jl#L187) if the location has homogeneous dynamics.
Ideally, we would just pass the location. That code part should not care about the dynamics at all.

**Comment by schillic** [comment]
The best solution here is to get rid of our internal system representation and use the systems from `MathematicalSystems`. Then we can just pass the modes, which are `(Constrained)AffineSystem`s or similar, to the continuous-post operator directly. This also removes the need to unpack the invariant in the hybrid loop.

**Comment by mforets** [comment]
> The best solution here is to get rid of our internal system representation and use the systems from MathematicalSystems. 

Agreed. I began to get rid of the old `ContinuousSystem / DiscreteSystem` in `discretize.jl` [here](https://github.com/JuliaReach/Reachability.jl/pull/503).
