### ISSUE TITLE
Remove invariant argument from continuous-post operators

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#507]
This is a follow-up of #491.
Since we pass an arbitrary system now, the invariant is encapsulated in that system and the callee does not need a separate argument for the invariant anymore.
This needs to be accounted for in the discretization.

**Comment by mforets** [comment]
We can use `Universe` instead of `nothing` when there are no constraints.

**Comment by mforets** [comment]
Note that afte https://github.com/JuliaReach/Reachability.jl/pull/542, the state set `X` is normalized to being a `LazySet` (`Universe` if it was passed as a `Nothing`).

Moreover, as you said above we may also delete the `invariant` argument in `solve!`.

**Comment by schillic** [comment]
Note that we currently completely ignore constrained continuous systems (`solve` calls `solve!` without any invariant). This will get automatically fixed if we remove this argument :+1:
