### ISSUE TITLE
Discretize using concrete operations with zonotopes

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#512]
For the zonotopes set representation, Minkowski sum and linear map can be computed efficiently. The proposal is to offer a way to compute

```julia
Ω0 = ConvexHull(X0, ϕ*X0 ⊕ δ*U ⊕ □α)
```
in discretize returning the convex hull of two zonotopes. Then, we can use the existing function in  `LazySets.Approximations.overapproximate` to convert it back to a zonotope.

**Comment by mforets** [comment]
This option applies to different approximation models, so i think that it is better to add it as a separate option. What woud be a good name? The option refers to the set type, or representation, used for the initial states and for the transformed inputs. Now we are using "lazy" set types: the initial states of the discretized system are a lazy convex hull.

**Comment by schillic** [comment]
We can add a new `algorithm`, for instance of the name `"zonotopes"`.
