### ISSUE TITLE
Use lazy SymmetricIntervalHull

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#52]

**Comment by mforets** [comment]
let `sih = lazy_sih ? SymmetricIntervalHull : symmetric_interval_hull` and update `discr_bloat_interpolation` accordingly. 

then

479.857893 seconds (2.46 M allocations: 111.611 GiB, 2.21% gc time)
and
317.995036 seconds (1.38 M allocations: 93.809 GiB, 2.56% gc time)

are the times for `lazy_sih` being `false` and `true` respectively. 

the extraction of `Phi2Aabs` still takes a lot of time.

**Comment by schillic** [comment]
I had hoped for more, but still an improvement of 1/3 👍

**Comment by schillic** [comment]
The savings in the discretization are lost again in the decomposition. Currently all our decomposition methods use at least box approximation (`Interval`, `Hyperrectangle`, `HPolygon`). Thus we anyway have to compute the boxes, and the lazy symmetric interval hull just adds a small overhead.
Example for FOM and MNA5:

| model | `lazy_sih` | discretization | decomposition | sum |
|-|-|-|-|-|
| FOM with `lazy_expm` mode | yes | 0.16 | 1.82 | 1.98 |
|  | no | 0.33 | 1.13 | 1.98 |
| FOM without `lazy_expm` mode | yes | 5.20 | 2.01 | 7.21 |
|  | no | 6.64 | 0.57 | 7.21 |
| MNA5 | yes | 192 | 482 | 674 |
|  | no | 339 | 338 | 677 |

Hence we should not activate this option by default.
