### ISSUE TITLE
Accept lazyset for a constant input

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#520]
The "canonical" system type for BFFPSV18 algorithm is a `ConstrainedLinearControlContinuousSystem` with matrix `A`, identity matrix `B`, Universal set (or nothing ATM) or a lazyset for the constraints `X`, and finally a `<:AbstractInput` for the inputs.

For convenience, i believe that it is good if we accept (again, but this time using MathematicalSystems types!) a LazySet for the place of `U` constraint. However, i'm not sure where it would be a good place to make this preprocessing.

**Comment by schillic** [comment]
This algorithm-independent preprocessing of the model would be the first thing to do in `solve`. In the future there may be more preprocessing steps, so we should wrap this in a function (better even in a new file).
