### ISSUE TITLE
LazyDiscretePost works very slow in master branch

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/Reachability.jl#536]
Here is results for Filtered oscilator model with n=16:
ConcreteDiscretePost: 5.6 seconds
ApproximatingDiscretePost: 41.078710
LazyDiscretePost: 186.067070
Both Reachability and LazySets on latest commits on master branch

**Comment by mforets** [comment]
Thanks for the report! Comparing with the results table, seems like the regression does not only affect `LazyDiscretePost`:

<img width="723" alt="Screen Shot 2019-03-11 at 19 34 25" src="https://user-images.githubusercontent.com/12424594/54162629-e572b980-4434-11e9-9c1e-b068a9f658a7.png">

@kostakoida which exact script are you using? I'll try the one in [ReachabilityBenchmarks](https://github.com/JuliaReach/ReachabilityBenchmarks/blob/master/models/SpaceEx/FilteredOscillator/FilteredOscillator.jl)...

**Comment by kostakoida** [comment]
@mforets Yes, I used exactly the same script.

**Comment by kostakoida** [comment]
Seems that the problem is in fix-point check. If you restrict number of jumps to 5, it works as before. In addition, `one_loop_iteration` also restricts number of jumps correctly. So, I am not sure what is correct functionality: what we had before or what we have now. In other words, Do we expect to see more jumps with increasing the dimension of our model.

**Comment by schillic** [comment]
Okay, then everything is fine and you just need to benchmark with the option `one_loop_iteration`.
Then old benchmark corresponds to the setting where this option is set to `true` :wink:

**Comment by mforets** [comment]
Good, should we update the ReachabilityBenchmarks script or not?

**Comment by schillic** [comment]
I would say "no." This option was not part of the "original" model.

**Comment by mforets** [comment]
Ok to keep the option as `false` by default. I added a note in https://github.com/JuliaReach/ReachabilityBenchmarks/pull/90 for the update in the Readme. 

> So, I am not sure what is correct functionality: what we had before or what we have now.

I would say that both of them are correct. But we can add more more details in the `filtered_oscillator` [docstring](https://github.com/JuliaReach/ReachabilityBenchmarks/blob/master/models/SpaceEx/FilteredOscillator/FilteredOscillator.jl#L13).

**Comment by mforets** [comment]
> But we can add more more details in the filtered_oscillator docstring.

Let's continue in https://github.com/JuliaReach/ReachabilityBenchmarks/issues/91.
