### ISSUE TITLE
Simplify overapproximation option in BFFPSV18

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#628]
[get_overapproximation_option](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/DiscretePost/DiscretePost.jl#L107) in the discrete post is there to make the transformation from template directions symbols (alias) to arguments that are accepted by LazySets `overapproximate`. In https://github.com/JuliaReach/LazySets.jl/issues/1329 it is proposed to move that part directly to LazySets. Then `get_overapproximation_option` can be dropped with the advantage that future updates in LazySets overapproximate are available.

In the meantime, PR https://github.com/JuliaReach/Reachability.jl/pull/627 allows to use template dirs in the discrete post by adding more checks.

**Comment by schillic** [comment]
In #633 I remove these symbols for simplicity.
