### ISSUE TITLE
Add arXiv paper

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#63]
* [x] to [References](https://github.com/JuliaReach/Reachability.jl/wiki/References)
* [x] to [About](https://github.com/JuliaReach/Reachability.jl/blob/master/docs/src/about.md)
* [ ] PR in julialang publications

**Comment by mforets** [comment]
besides i'll file a PR as suggested here: https://julialang.org/publications/

**Comment by mforets** [comment]
> Reach Set Approximation through Decomposition with Low-dimensional Sets and High-dimensional Matrices
Sergiy Bogomolov, M. F., Goran Frehse, Andreas Podelski, Christian Schilling, Frédéric Viry.
In [21st ACM International Conference on Hybrid Systems: Computation and Control](https://www.hscc2018.deib.polimi.it/), 2018 Edition (Porto, Portugal). [aXiv pre-print](https://arxiv.org/abs/1801.09526)
Keywords: reachability analysis, safety verification, linear time-invariant systems, set recurrence relation

**Comment by mforets** [comment]
> besides i'll file a PR as suggested here: https://julialang.org/publications/

i'll prefer to wait a bit more, 'till it is actually published and it has a DOI..
