### ISSUE TITLE
Improve plots recipe

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#66]
As seen [here](https://discourse.julialang.org/t/plotting-thousands-of-polygons/9066/7) NaN separators are more efficient than a `@series` in a tight loop.

Besides it would be nice to compare the speed for our use case with GMT as plotting backend, also suggested in that thread.

**Comment by schillic** [comment]
I noticed that with the new recipe, we do not plot polygons anymore. Instead we plot a series of lines connecting the vertices of the polygon, but the last line is missing. Try plotting a rectangle - it will be open on one side. The polygons also do not have a fill color anymore, which might also be bad. We can get that back with the following options (maybe some of them are not needed): `color=:auto, fillcolor=:auto, alpha=0.5, fillalpha=0.3, seriestype=:shape`

**Comment by mforets** [comment]
`alpha` and `fillalpha` are not the same?

**Comment by mforets** [comment]
> alpha and fillalpha are not the same?

yes,

```julia
julia> plotattr("seriesalpha")
seriesalpha {Number in [0,1]}
alpha, opacity, seriesalphas, α

The alpha/opacity override for the series.  `nothing` (the default) means it will take the alpha value of the color.
Series attribute,  default: nothing
```

**Comment by mforets** [comment]
<img width="543" alt="screen shot 2018-02-16 at 12 13 38" src="https://user-images.githubusercontent.com/12424594/36314244-fb909c2c-1312-11e8-9b71-418485782377.png">

**Comment by mforets** [comment]
with the options:

```julia
@recipe function plot_sol(sol::ReachSolution{HPolygon};
                          seriescolor=:auto, fillcolor=:auto,
                          seriestype := :shape,
                          label="", grid=true, alpha=0.5,
                          indices=nothing, vars=nothing)
```

the problem is that for a large number (20k) the picture gets black, because of the borders of the rectangles (`fillcolor` option)..

**Comment by schillic** [comment]
Okay, maybe it does not work with `:auto` (I did not test it), but we can just write "blue" in both cases (I guess?). In general there must be an option to change the color of the borders, and if we use that, we should see an all-blue plot.
I think we should make that an option. Sometimes you want to see the shapes.

**Comment by mforets** [comment]
> because of the borders of the rectangles (fillcolor option)..

correction: this is the  `linecolor` option. the `linecolor="black"` is the default one in this case (using `seriestype := :shape`). we can use `linecolor = :match` so that it uses the same color as the filled plots.

as a rule of thumb i would use "black" for N < 300 and "match" for N > 300.

**Comment by schillic** [comment]
Thanks for your efforts, this is really cool 👍
