### ISSUE TITLE
Inconsistent behavior of GLGM06 across (in)homogeneous cases

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#680]
In the homogeneous case, we use an algorithm with wrapping effect:
https://github.com/JuliaReach/Reachability.jl/blob/29f5a2ce7842c5678a6cf88954924aacffeaa7fe/src/ReachSets/ContinuousPost/GLGM06/reach.jl#L19

In the inhomogeneous case, we use an algorithm without wrapping effect (except in the inputs):
https://github.com/JuliaReach/Reachability.jl/blob/29f5a2ce7842c5678a6cf88954924aacffeaa7fe/src/ReachSets/ContinuousPost/GLGM06/reach.jl#L51

**Comment by mforets** [comment]
> In the homogeneous case, we use an algorithm with wrapping effect:

in this scenario, the linear map is exact, so i don't expect to see a difference between recursive and not. in fact the call to [reduce_order](https://github.com/JuliaReach/Reachability.jl/blob/29f5a2ce7842c5678a6cf88954924aacffeaa7fe/src/ReachSets/ContinuousPost/GLGM06/reach.jl#L20) in the following line is not needed.

**Comment by mforets** [comment]
do reopen if you disagree :)
