### ISSUE TITLE
Solve stops before time horizon in TMJets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#700]
The solution of a nonlinear system with TMJets stops the simulation before the time horizon in some cases. For instance, in the [Lorenz model](https://github.com/JuliaReach/ReachabilityBenchmarks/pull/164),

```julia
sol.Xk[end].t_end

0.09422875648577093
```

**Comment by mforets** [comment]
Actually, the problem is that by default we don't print the `info`, which is in [this line](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/ContinuousPost/TMJets/reach.jl#L123). Hence, in the model referenced above we were just not using enough maximum steps.

So i would suggest that we wither change that line with an error, or return the computed flowpipe until max_steps but always print a message. 

Thanks @lbenet for helping me to understand this.

**Comment by mforets** [comment]
I will go for using the [warning level](https://github.com/JuliaReach/Reachability.jl/blob/master/src/logging.jl#L34) message, because this is shown by default, and one still recovers the computed flowpipe prior to stopping, which seems useful to have.

**Comment by lbenet** [comment]
> I will go for using the warning level message, because this is shown by default, and one still recovers the computed flowpipe prior to stopping, which seems useful to have.

Thanks for reporting. I agree that it might be better to have some sort of warning/info message, and then return the so-far obtained solution. I'll take care of this.

**Comment by mforets** [comment]
No problem, note that a fix is proposed in mforets/700. For reasons discussed elsewhere, this package has its own copy of validated integ.
