### ISSUE TITLE
Allow more general block structures

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#73]
Note that we assume `b == 2` in many places. They have to be identified and generalized.
A roadmap could be:

1. allow 1D decomposition
   * maybe add an `Interval` set type
2. allow mixed 1D/2D decomposition
3. allow arbitrary decomposition (involves high-dimensional set operations)
   * `Hyperrectangle`s
   * `HPolytope`s
      * mixture of `HPolygon`s and `HPolytope`s for mixed block sizes

**Comment by schillic** [comment]
We mainly have to revise the `blocks` input option. Currently it is an array containing the indices of the 2D blocks of interest. Now we need a way to say which decomposition we want, and in addition the variables that are interesting.

Proposal: Add two options:
1. `block_structure` represents the block structure for decomposition, which a normal user would probably not want to specify (default: 2D).
2. `variable_selection` represents the "output variables" (we already have `output_variables`, but this option must be 2D).

Then we also need a routine to compute the value of the old `blocks` option (i.e., the blocks we have to compute). We should give the user the option to pass those in order to benchmark the savings; possible name: `block_selection`.

**Comment by mforets** [comment]
> 1. block_structure represents the block structure for decomposition, which a normal user would probably not want to specify (default: 2D).

ok

> variable_selection represents the "output variables" (we already have output_variables, but this option must be 2D).

if we need to specify variables that we are interested in use `vars=...` (see list of options [here](https://github.com/JuliaReach/Reachability.jl/issues/12#issuecomment-346954788))

> Then we also need a routine to compute the value of the old blocks option (i.e., the blocks we have to compute). We should give the user the option to pass those in order to benchmark the savings; possible name: `block_selection`

or just keep `blocks`, as in `blocks = [1, 2, 3]`. this routine is important because it will check if blocks and variables are consistent if they are both given!

**Comment by schillic** [comment]
Should `vars` be a `Tuple` as in the link? Or rather an `AbstractVector`? Or a `Union` of both? Then we should probably use type aliases to avoid writing this union all the time.

**Comment by mforets** [comment]
There was an argument for `AbastractVector`, that we can easily define comprehension. Besides we also use vectors for blocks so i would just stick to that choice.

**Comment by schillic** [comment]
Current state: We want to have the following input options:
* `vars::AbstractVector{Int}` - variables we are interested in
* `blocks::AbstractVector{Int}` - block partition; elements are 2D vectors containing the start and end index of a block (optional, default to all blocks)
* `block_types::Dict{S, AbstractVector{<:AbstractVector{Int}}} where {S<:LazySet}` - a mapping from set types to blocks (optional, default to `Interval` for 1D and `Hyperrectangle` for mD blocks)

**Comment by mforets** [comment]
alternatively, default `block_types` could be `Hyperrectangle` (both for 1D and for mD).

**Comment by mforets** [comment]
i don't have a particular preference. ultimately the default could depend on the algorithm implementation or performance.

**Comment by schillic** [comment]
`Interval` should be faster (otherwise we should investigate why not).
