### ISSUE TITLE
Interval arithmetic implementation for 1D blocks

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#74]
This is both more efficient and sound.
Preliminary: first part of #73

Basically this should work out of the box if we use 1D blocks and have a type for intervals in `LazySets`.

**Comment by schillic** [comment]
This is now supported, but the performance is in fact slightly worse than with `Hyperrectangle`s. We should have a look, but I am not surprised, at least for dense models. What is suspicious is that for sparse models, where I would have suspected a speedup, we get *a lot* slower (but independently of `Interval`s). This is considered in #111.

**Comment by mforets** [comment]
Should we close this?

**Comment by schillic** [comment]
Yes. I was thinking if at some point we want to support interval arithmetic during the whole workflow, but we should open a new issue for that.
