### ISSUE TITLE
Merge x_explicit_block functions

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#75]
Currently we have
- three methods for single-block reachability with inputs (sparse, dense, and lazy mexp),
- three respective methods for single-block reachability without inputs,
- three respective methods for multi-block reachability with inputs,
- three respective methods for multi-block reachability without inputs, and
- twelve respective methods for property checking.

We could easily merge certain functions with similar behavior by adding further option parameters and case distinctions. Julia can compile them away without losing performance.

I propose to merge any subset of {"1. reach and check", "2. with and without inputs", "3. single-block and multi-block"}. If we want more than one merge, we should probably do one change after the other. In particular, if we merge all, we will end up with only three functions!
Proposed changes:
1. add one Boolean flag `reach` (or better an [`@enum`](https://docs.julialang.org/en/stable/stdlib/base/#Base.Enums.@enum) with values `reach` and `check`)
2. change the type of `U` to `Union{ConstantNonDeterministicInput, Void}` and pass `nothing` for homogeneous systems
3. add one Boolean flag `single_block` (or better again an `@enum`) and always pass `blocks` even for single-block analysis

(possibly helpful: [Types with values-as-parameters](https://docs.julialang.org/en/stable/manual/performance-tips/#Types-with-values-as-parameters-1))
(See [this blog post](https://pixorblog.wordpress.com/2018/02/23/julia-dispatch-enum-vs-type-comparison/) for a type alternative to `@enum`, but it has the same performance.)

We should double-check with [`@code_warntype`](https://docs.julialang.org/en/stable/manual/performance-tips/#man-code-warntype-1) and by looking at the generated code that the case distinctions are really not present in the generated code.

Benefit: Smaller code base, meaning less changes required in the future. This is particularly helpful before doing #73 where we need to change lots of things.

And while we are at it:
What about renaming the methods `reach_explicit_block` → `reach_block`?
What about splittling the methods into different files (depending on which ones we merge)?

**Comment by mforets** [comment]
>  What about renaming the methods reach_explicit_block → reach_block?

ok

>  What about splittling the methods into different files (depending on which ones we merge)?

we now have `reach_explicit_block`, `reach_explicit_blocks` and similarly for `check`. after the proposed updates in this issue, we'll have `reach_block` and `check_block`, since basicaly we would be merging block and blocks, is this correct?

i also like the idea of merging analogue `reach` and `check` specializations, see for example the code below. however, there are some difficulties:

- different signature (check needs a property)
- different output type (check outputs a number while reach modifies the `res` vector and outputs nothing)
- the initialization and the main loop of `check` uses calls to `check_property`


```julia
# sparse, with input
function check_explicit_block!(ϕ::SparseMatrixCSC{NUM, Int},
                               Xhat0::Vector{<:LazySet{NUM}},
                               U::ConstantNonDeterministicInput,
                               overapproximate::Function,
                               n::Int,
                               b::Int,
                               N::Int,
                               bi::Int,
                               prop::Property)::Int where {NUM}
    if !check_property(Xhat0[bi], prop)
        return 1
    elseif N == 1
        return 0
    end

    @inline F(bi::Int, bj::Int) = ϕpowerk[(2*bi-1):(2*bi), (2*bj-1):(2*bj)]
    @inline G0(bi::Int) = sparse(1:2, (2*bi-1):(2*bi), [1., 1.], 2, n)
    @inline Gk(bi::Int) = ϕpowerk[(2*bi-1):(2*bi), :]

    inputs = next_set(U)
    Whatk = overapproximate(G0(bi) * inputs)
    ϕpowerk = copy(ϕ)

    dummy_set = ZeroSet(2)

    k = 2
    @inbounds while true
        Xhatk_bi = dummy_set
        for bj in 1:b
            if findfirst(F(bi, bj)) != 0
                Xhatk_bi = Xhatk_bi + F(bi, bj) * Xhat0[bj]
            end
        end
        if !check_property(Xhatk_bi + Whatk, prop)
            return k
        elseif k == N
            break
        end

        Whatk = overapproximate(Whatk + Gk(bi) * inputs)
        ϕpowerk = ϕpowerk * ϕ
        k += 1
    end

    return 0
end
```

```julia
# sparse, with input
function reach_explicit_block!(ϕ::SparseMatrixCSC{NUM, Int},
                               Xhat0::Vector{<:LazySet{NUM}},
                               U::ConstantNonDeterministicInput,
                               n::Int,
                               b::Int,
                               N::Int,
                               overapproximate::Function,
                               bi::Int,
                               res::Vector{<:LazySet{NUM}}
                              )::Void where {NUM}
    res[1] = Xhat0[bi]
    if N == 1
        nothing
        return
    end

    @inline F(bi::Int, bj::Int) = ϕpowerk[(2*bi-1):(2*bi), (2*bj-1):(2*bj)]
    @inline G0(bi::Int) = sparse(1:2, (2*bi-1):(2*bi), [1., 1.], 2, n)
    @inline Gk(bi::Int) = ϕpowerk[(2*bi-1):(2*bi), :]

    inputs = next_set(U)
    Whatk_bi = overapproximate(G0(bi) * inputs)
    ϕpowerk = copy(ϕ)

    dummy_set = ZeroSet(2)

    k = 2
    @inbounds while true
        Xhatk_bi = dummy_set
        for bj in 1:b
            if findfirst(F(bi, bj)) != 0
                Xhatk_bi = Xhatk_bi + F(bi, bj) * Xhat0[bj]
            end
        end
        res[k] = overapproximate(Xhatk_bi + Whatk_bi)

        if k == N
            break
        end

        Whatk_bi = overapproximate(Whatk_bi + Gk(bi) * inputs)
        ϕpowerk = ϕpowerk * ϕ
        k += 1
    end

    nothing
end
```

**Comment by schillic** [comment]
I agree that it is not trivial and may become too complicated.

Another option would be to use macros to have some common code and generate the different methods automatically. Basically this should generate the existing functions, but the good thing is that we have only *few* actual source code copies.

**Comment by mforets** [comment]
Most probably, using macros for the specialization is the best practice. I'm not close to writing down a solution for the example i gave above, so i don't mind if we leave this for a future release.

**Comment by schillic** [comment]
We should evaluate the single block analysis performance. If it is not much better, we can just throw it away.

**Comment by mforets** [comment]
tests show that the new `schillic/73` with multi-block can substitute the single-block analysis.
that will cut the number of functions by half. i'm less enthusiastic about merging check/reach, dense/sparse, or input/no input.

**Comment by schillic** [comment]
We have merged single-/multiblock and with/without inputs and are now down to six versions.
Currently we consider this enough (e.g., to keep the code still readable).
