### ISSUE TITLE
Property failure for a random matrix in unit tests

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#81]
[This commit](https://github.com/JuliaReach/Reachability.jl/commit/06b33193bee04379ab8351100e0f892ad92591e5#diff-bf70ec8cec2603f3e1e62b16c196ad7cR21) added unit tests which do not generally hold because `A` is a random matrix.

@mforets: Do you agree that we should fix `A`?

**Comment by mforets** [comment]
we can fix 

```julia
A = [ 0.0509836  0.168159  0.95246   0.33644
 0.42377    0.67972   0.129232  0.126662
 0.518654   0.981313  0.489854  0.588326
 0.38318    0.616014  0.518412  0.778765]
```
