### ISSUE TITLE
Fix plotting for non-polygons

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#83]
This problem is the same as [here](https://github.com/JuliaReach/LazySets.jl/pull/276).

proposal:

```julia
@recipe function plot_sol(sol::ReachSolution{<:AbstractPolytope};
                          seriescolor=:auto,
                          fillcolor=:auto,
                          seriestype=:shape,
                          label="", grid=true, alpha=0.5,
                          indices=nothing, vars=nothing)

    options = check_aliases_and_add_default_value(sol)

    if vars != nothing
        vars = add_plot_labels(vars)
        xguide --> vars[1]; yguide --> vars[2]
    elseif options.dict[:plot_vars] != nothing
        vars = add_plot_labels(options.dict[:plot_vars])
        xguide --> vars[1]; yguide --> vars[2]
    end

    if indices == nothing
        indices = options.dict[:plot_indices]
    end

    N = length(indices)
    # rule of thumb for linecolor and fillcolor overlap when plotting many sets
    if N < 300
        linecolor --> :black
    else
        linecolor --> :match
    end

    # Using single list and NaN separators
    vlist = Vector{Vector{Float64}}()
    if sol.Xk[1] isa AbstractPolygon
        for i in indices
            append!(vlist, vertices_list(sol.Xk[i]))
            push!(vlist, [NaN; NaN])
        end
    else
         for i in indices
              append!(vlist, convex_hull(vertices_list(sol.Xk[i])))
              push!(vlist, [NaN; NaN])
         end
    end
    vlist = hcat(vlist...)'
    vlist[:, 1], vlist[:, 2]

end
```

**Comment by schillic** [comment]
Is it not possible to just fall back to the plot recipe from `LazySets`?

**Comment by mforets** [comment]
that would be better, but i don't know how to put a plot recipe inside another one.

**Comment by schillic** [comment]
Interestingly, if you remove everything below `vlist = ...` and just return `sol.Xk`, it plots the sets, but ignores the settings. In particular, the hyperrectangle plot is fixed (thus it uses the one from `LazySets`).

**Comment by mforets** [comment]
interesting. still i cannot make it keep the settings even if it is inside a `@series` block.

**Comment by schillic** [comment]
Yes, I assume that the idea is: If you have a plot recipe for an unwrapped type, you do not want to use different settings.
But at least if passes the options you give: `plot(s, seriescolor="blue")` plots a blue series.

**Comment by mforets** [comment]
.... it's `sort = !(sol.Xk[1] isa AbstractPolygon)` !

**Comment by schillic** [comment]
When I tried to call `plot` from the recipe, it crashed.

**Comment by mforets** [comment]
really? it works here, can you try again?

**Comment by schillic** [comment]
In any way we should use the `NaN`s in `LazySets` for vectors. I will add an issue.
