### ISSUE TITLE
Inconsistent lazy mexp reach/check versions

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#89]
The `reach` versions use the "sparse" analysis, while the `check` versions use the "dense" analysis.

@mforets: Do you see a reason for this?

**Comment by mforets** [comment]
In general the matrix exp even of a sparse matrix will be dense, thus i don't see a reason for keeping the sparse analysis -- yes it *could* be useful in some cases but i think it will be a small subset of cases.

**Comment by schillic** [comment]
I think we should rather offer both versions, just as we do with "sparse" and "dense" without lazy_expm mode. The difference between sparse and dense is very subtle, so maybe we can merge them in #75.

**Comment by mforets** [comment]
Agreed. I haven't checked the result for MNA5 using the sparse analysis.

**Comment by mforets** [comment]
do you mean inner or outer loop?

**Comment by schillic** [comment]
Currently it is in the outer loop (over k), but we should call `get_rows` only once.
