### ISSUE TITLE
Revise add_dimension

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#93]
Currently we make the dimension even by adding a dummy dimension. However, we can now approach odd dimensions naturally. So we should remove this part and instead only check that the `partition` is consistent with the dimension.

**Comment by schillic** [comment]
If we add a dimension, we also have to modify the partition. Currently for odd dimension and `HPolygon` decomposition, we crash because the last block has size 1, which is not supported by the decomposition function in `LazySets`.

**Comment by mforets** [comment]
yes, i agree that we remove the call to `add_dimension` in `solve` (or `reach`).

**Comment by schillic** [comment]
Just removing it will not resolve the above-mentioned problem. The question is if this is a user-error (because you cannot use a polygon for a 1D block) or if we want to capture and resolve this case automatically.
In the second case, having #87 would simplify things here.

**Comment by schillic** [comment]
Now it is also broken for non-`HPolygon` decomposition:
```julia
ERROR: LoadError: MethodError: no method matching length(::Systems.ConstantInput{LazySets.LinearMap{Float64,Float64}})
```
