### ISSUE TITLE
Lazy mexp version assigns immutable field

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#96]
In `schillic/73`:
```julia
ERROR: LoadError: type is immutable
Stacktrace:
 [1] reach_blocks!(...) at .../src/ReachSets/reach_blocks.jl:336
```

This corresponds to [this line](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/reach_explicit_blocks.jl#L356).

Possible solutions:
1. Store the matrix outside (not sure if this works).
2. Make a copy (might be expensive).
3. Make the type mutable.

**Comment by mforets** [comment]
4. Update the matrix inplace: `@. ϕpowerk.M = ϕpowerk.M  + ϕ.M`.
